### ISSUE TITLE
Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by samuelms1** [kirbysayshi/vash-express-example#2]
I get this error "Maximum call stack size exceeded." when using this example.  If I go to ./routes/index.js and change the for loop to be smaller (like 20) it works fine.

**Full error:**

Connect
500 RangeError: Problem while rendering template at line 23, character 2.
Original message: Maximum call stack size exceeded.
Context:
   21 |     })
   22 |
 > 23 | })
   24 |
   at Buffer.pushConcat (c:\Users\sasmith\Source\Repos\test\vash-express-example\node_modules\vash\build\vash.js:1640:18)
   at helpers.finishLayout (c:\Users\sasmith\Source\Repos\test\vash-express-example\node_modules\vash\build\vash.js:2125:25)
   at Object.onRenderEnd (c:\Users\sasmith\Source\Repos\test\vash-express-example\node_modules\vash\build\vash.js:2083:9)
   at eval (eval at <anonymous> (c:\Users\sasmith\Source\Repos\test\vash-express-example\node_modules\vash\build\vash.js:1820:24), <anonymous>:462:44)
   at linked (c:\Users\sasmith\Source\Repos\test\vash-express-example\node_modules\vash\build\vash.js:1860:12)
   at c:\Users\sasmith\Source\Repos\test\vash-express-example\node_modules\vash\build\vash.js:2082:21
   at Object.vash.loadFile (c:\Users\sasmith\Source\Repos\test\vash-express-example\node_modules\vash\build\vash.js:2070:10)
   at View.vash.renderFile [as engine] (c:\Users\sasmith\Source\Repos\test\vash-express-example\node_modules\vash\build\vash.js:2078:8)
   at View.render (c:\Users\sasmith\Source\Repos\test\vash-express-example\node_modules\express\lib\view.js:126:8)
   at tryRender (c:\Users\sasmith\Source\Repos\test\vash-express-example\node_modules\express\lib\application.js:639:10)

**Comment by samuelms1** [comment]
Also, if you edit index.vash to not have the @html.extend('layout') and @html.extend('content') calls, then it works fine even with 1000 iterations.  So, if index.vash looks like this:

        <h2>@model.channel</h2>

        <table class="table table-bordered">
            @model.buffer.forEach(function(msg){
                <tr>
                    <td>
                        @msg.nick
                    </td>
                    <td>
                        <small class="timestamp">@msg.date</small>
                        @msg.args[1]
                    </td>
                </tr>
            })
        </table>

Of course then the layout isn't applied, so that's not ok.

**Comment by kirbysayshi** [comment]
Hi! I think the problem was that this example was using an old version of vash. If you pull the latest changes, or just `npm install vash@latest` you should not longer get this error.

Sorry for the delay in responding!
